import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

//componennt
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import ClarityScript from "@/components/ClarityScript"


const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetBrainsMono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const projectId = "ozjgblsi0g"
  // Clarity.init(projectId);
  // Clarity.identify("user-id", "deep"); // only custom-id is required
  // Clarity.setTag("Header", "header");
  // Clarity.consent()
  // Clarity.upgrade("reason");
  return (
    <html lang="en">
      <body className={jetBrainsMono.variable}>
        <ClarityScript/>
        <Header />
        <StairTransition/>
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
// pages/_not-found.js or pages/404.js
export default function NotFoundPage() {
  return <h1>Page Not Found</h1>;
}
